server:
  port: ${PORT:8080}

spring:
  application:
    name: user-services
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false


database:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/usuario_db}
  driver-class-name: org.postgresql.Driver
  user: ${DATABASE_USER:fatura_user}
  pass: ${DATABASE_PASS:fatura_user}
  default_schema: ${DATABASE_SCHEMA:public}

message:
  baseName: message

security:
  enabled: ${SECURITY_ENABLE:true}
  secret:
    vault:
      endpoint: ${VAULT_ENDPOINT:http://127.0.0.1:8200}
      role-id: ${VAULT_ROLE_ID:84872589-3e16-853b-f530-5054f3f4c549}
      secret-id: ${VAULT_SECRET_ID:54f73290-2dda-5a66-821a-dca8fa00e977}
  scopes: ${APP_SCOPES:users}

cache:
  redis:
    config:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:599E72B4E2ED1023E6EE0842668117E704F5A912B09369F1AD300147E2CA895C}
    caches:
      - cacheName: user_services_cliente_por_email
        expiration: ${CACHE_DURATION_CONSULTA_PESSOA_EMAIL:PT72H}
      - cacheName: user_services_cliente_login_email
        expiration: ${CACHE_DURATION_CONSULTA_LOGIN_EMAIL:PT72H}
      - cacheName: user_services_cliente_por_id
        expiration: ${CACHE_DURATION_CONSULTA_LOGIN_EMAIL:PT168H}