CREATE SEQUENCE USUARIO_ID_SEQ MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE TYPE DOMINIO_STATUS AS ENUM ('PENDING', 'ACTIVE', 'INACTIVE');

CREATE TABLE IF NOT EXISTS TB_USER
(
    ID           BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('USUARIO_ID_SEQ'),
    NAME         VARCHAR (256) NOT NULL,
    EMAIL        VARCHAR (256) NOT NULL,
    PWD          VARCHAR (550) NOT NULL,
    STATUS	     VARCHAR (50)  NOT NULL DEFAULT 'ACTIVE',
    DT_CADASTRO  DATE DEFAULT NOW(),
    DT_UPDATE DATE,
    UNIQUE(EMAIL)
);

CREATE TABLE IF NOT EXISTS TB_ROLE
(
    ID VARCHAR (50) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_USER_ROLE
(
    ID_USER BIGINT NOT NULL,
    ID_ROLE VARCHAR (50) NOT NULL,

    FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID),
    FOREIGN KEY (ID_ROLE) REFERENCES TB_ROLE(ID)
);

-- INSERT

INSERT INTO public.tb_role VALUES ('ROLE_ADMIN');
INSERT INTO public.tb_role VALUES ('ROLE_USER');
INSERT INTO public.tb_role VALUES ('ROLE_APPLICATION');

INSERT INTO public.tb_user (NAME, EMAIL, PWD) VALUES ('Siron Silva', 'sirondba@gmail.com', '$2a$10$vlUpoD3T8/mIaCbE5hDNeOJM1Vrbv8KqHDNPgpoqNUZ9CmeSVPTUm');
INSERT INTO public.tb_user_role  VALUES ((select id from TB_USER u where u.email = 'sirondba@gmail.com'), 'ROLE_ADMIN');


