CREATE TABLE IF NOT EXISTS TB_USER
(
    ID           serial NOT NULL,
    NAME         VARCHAR (256) NOT NULL,
    EMAIL        VARCHAR (256) NOT NULL,
    PASSWORD     VARCHAR (256) NOT NULL,
    STATUS	     VARCHAR (256) NOT NULL,
    UNIQUE(EMAIL),    
    CONSTRAINT pk_user primary key (ID)
);