name: heroku-caderneta-user

on:
  push:
    branches: [ main ]

jobs:

    compile:
        runs-on: ubuntu-latest
        name: Running Java ${{ matrix.java }} compile
        steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11.0.4
        - name: Compile code
          run: mvn compile
          
    test:
        runs-on: ubuntu-latest
        name: Running tests
        needs: compile
        steps:
          - uses: actions/checkout@v1
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: 11.0.4
          - name: Run unit tests
            run: mvn test
            
    deploy:
        runs-on: ubuntu-latest
        name: Deploy Heroku
        needs: test
        steps:
        - uses: actions/checkout@v2
        - name: Deploy to Heroku
          uses: AkhileshNS/heroku-deploy@v3.8.8
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            heroku_app_name: ${{secrets.HEROKU_APP}}
            
    docker:
        name: Publish - Docker Hub
        runs-on: ubuntu-18.04
        needs: [deploy]
        steps:            
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11.0.4
        - name: Publish to Docker Hub
          uses: docker/build-push-action@v1
          with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
           repository: sirondba/caderneta-user-services
           tags: ${{github.run_number}}